AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AOAC Back end api

Globals:
  Function:
    MemorySize: 1024
    Runtime: go1.x
    Timeout: 15
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../app/lambda/v1/hello-world/
      Handler: hello-world
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/hello
            Method: GET

Outputs:
  HelloWorldAPI:
    Description: "Api Gateway endpoint for hello world"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn