### Create Admin
POST {{BASE_URL}}/{{VERSION}}/admin
x-api-key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profilepick"; filename="profilePick.jpg"

< ../../local/tree-736885__480.jpg

--WebAppBoundary
Content-Disposition: form-data; name="name"

Mahamadou

--WebAppBoundary
Content-Disposition: form-data; name="surname"

Samake

--WebAppBoundary
Content-Disposition: form-data; name="email"

{{EMAIL}}

--WebAppBoundary
Content-Disposition: form-data; name="phonenumber"

+337809643

--WebAppBoundary
Content-Disposition: form-data; name="role"

ADMIN

--WebAppBoundary
Content-Disposition: form-data; name="password"

{{PASSWORD}}
--WebAppBoundary--

### Get All Admin
GET {{BASE_URL}}/{{VERSION}}/admin?page=1&rowsPerPage=5
x-api-key: {{API_KEY}}
content-type: application/json

### Get By ID
GET {{BASE_URL}}/{{VERSION}}/admin/cd7176e5-02ed-4bfc-b04e-673aa07fdc34
x-api-key: {{API_KEY}}
content-type: application/json

### Login Admin
POST {{BASE_URL}}/{{VERSION}}/admin/login
x-api-key: {{API_KEY}}
content-type: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}"
}

### Refresh Admin Token
POST {{BASE_URL}}/{{VERSION}}/admin/login/refresh
x-api-key: {{API_KEY}}
content-type: application/json

{
  "id": "{{ID}}",
  "refreshToken": "{{REFRESH_TOKEN}}"
}

### Update Admin Info
PUT {{BASE_URL}}/{{VERSION}}/admin/{{ID}}
x-api-key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profilepick"; filename="profilePick.jpg"

< ../../local/picture.jpg

--WebAppBoundary
Content-Disposition: form-data; name="name"

Bathie

--WebAppBoundary
Content-Disposition: form-data; name="surname"

Alexandre

--WebAppBoundary--

### Delete Admin
DELETE {{BASE_URL}}/{{VERSION}}/admin/{{ID}}
x-api-key: {{API_KEY}}
content-type: application/json
