### Get All Admin
GET {{BASE_URL}}/{{VERSION}}/admin?rowsPerPage=10&page=1
x-api-key: {{API_KEY}}
content-type: application/json

### Get By ID
GET {{BASE_URL}}/{{VERSION}}/admin/{{ID}}
x-api-key: {{API_KEY}}
content-type: application/json

### Create Admin
POST {{BASE_URL}}/{{VERSION}}/admin
x-api-key: {{API_KEY}}
content-type: application/json

{
  "name": "Mahamadou",
  "surname": "samake",
  "email": "{{EMAIL}}",
  "phoneNumber": "+337809643",
  "role": "ADMIN",
  "profilePick": "test",
  "password": "{{PASSWORD}}"
}

### Login Admin
POST {{BASE_URL}}/{{VERSION}}/admin/login
x-api-key: {{API_KEY}}
content-type: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}"
}

### Refresh Admin Token
POST {{BASE_URL}}/{{VERSION}}/admin/login/refresh
x-api-key: {{API_KEY}}
content-type: application/json

{
  "id": "{{ID}}",
  "refreshToken": "{{REFRESH_TOKEN}}"
}

### Update Admin Info
PUT {{BASE_URL}}/{{VERSION}}/admin/{{ID}}
x-api-key: {{API_KEY}}
content-type: application/json

{
  "name": "Bathie",
  "surname": "Alexandre"
}

### Delete Admin
DELETE {{BASE_URL}}/{{VERSION}}/admin/{{ID}}
x-api-key: {{API_KEY}}
content-type: application/json
